yarnPath: .yarn/releases/yarn-4.0.2.cjs
cacheFolder: .yarn/cache
enableGlobalCache: false
nodeLinker: pnp
packageExtensions:
  "@storybook/nextjs@*":
    dependencies:
      "@babel/core": "*"
      webpack: "*"
